### Warm up

Import the numpy package under the name np and the matplotlib package under the name plt.

In [2]:
#Your code here

Create a 8x4 matrix with values ranging from 0 to 31

In [3]:
#Your code here

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


Calculate the mean value per column of the matrix you obtained .

In [7]:
#Your code here

[14. 15. 16. 17.]


Create a 3D NumPy array of uniformaly-distributed values between 10 and 20 and print the element at index (2, 0, 3).

In [14]:
#Your code here

[[[15.95737001 16.50439882 19.18081641 13.45275339]
  [16.2361727  12.32165913 12.19254018 11.19721133]]

 [[14.64888672 19.93716622 11.80141626 11.27479572]
  [17.22866173 14.15817277 18.85185298 19.16896329]]

 [[10.83618594 10.39339833 16.90804018 15.91397549]
  [12.19409233 17.93444429 10.95687867 18.15772866]]]

Element at index (1, 2, 3): 15.913975486327434


Create a 1D array containing values larger than 15 in the previous array. Hint: use fancy indexing and boolean arrays. 

In [15]:
#Your code here

array([15.95737001, 16.50439882, 19.18081641, 16.2361727 , 19.93716622,
       17.22866173, 18.85185298, 19.16896329, 16.90804018, 15.91397549,
       17.93444429, 18.15772866])

Perform element-wise division of arr1 and arr1, print the result and its shape.

In [4]:
arr1 = np.random.rand(2, 3, 4)
arr2 = np.arange(1, 25).reshape(2, 3, 4)

In [5]:
#Your code here

[[[   2.24461885    3.81277454    7.82970132    8.60487052]
  [  11.40982485   11.09826935   11.4129458    10.4941003 ]
  [  14.94760854   14.94588322   13.327037     21.0754099 ]]

 [[ 127.88408173   83.35966965  160.44805241  105.48014179]
  [  18.10378342   23.24293234   30.50555884   27.83875308]
  [  25.45171185   22.05766041 2120.11252357  228.08325899]]]
(2, 3, 4)


### Bioinformatics challenge: the WAG protein subtitution matrix

The WAG substitution matrix combines two key elements: exchangeability parameters and amino acid frequencies. These come from a dataset of 3905 globular protein amino acid sequences.

Amino acid frequencies tell us how often each amino acid appears in the sequences. Exchangeability parameters show how amino acids replace each other over time. Each row in the exchangeability parameter matrix represents the substitution rates between one amino acid and all others.

These values are crucial for understanding how proteins evolve and are used in tasks like aligning sequences and studying evolutionary relationships.

The order of amino acids in the exchangeability parameter matrix matches their order in the amino acid frequencies list: Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, and Val.

the **rate matrix Q** is based on both the exchangability parameters and amino acid frequencies, and reflects the instantaneous rate of substitution between amino acids in a continuous-time Markov process.

In this exercise, we will generate the rate matrix Q based on using these exchangability parameters and frequencies.
###

The amino acid frequencies vector is given by:

In [8]:
p = np.array([0.0866279, 0.043972, 0.0390894, 0.0570451, 0.0193078, 0.0367281, 0.0580589, 0.0832518, 0.0244313, 0.048466, 0.086209, 0.0620286, 0.0195027, 0.0384319, 0.0457631, 0.0695179, 0.0610127, 0.0143859, 0.0352742, 0.0708956])


The exchangeability parameters are provided as a 20x20 lower triangular matrix in the file WAG.csv, with zeros in the diagonal. 
Import this file into a NumPy array named *M*. Utilize the np.loadtxt function and specify the encoding as 'utf-8-sig'. Make sure the matrix dimensions are indeed (20,20).

In [9]:
#Your code here

(20, 20)


Transform the lower diagonal matrix to a symmetrical matrix named S by replacing the upper triangular part, currently filled with zeros, with the symmetrical complement of the lower-dimensional matrix. Print the matrix S.

In [11]:
#Your code here

[[0.   0.55 0.51 0.74 1.03 0.91 1.58 1.42 0.32 0.19 0.4  0.91 0.89 0.21
  1.44 3.37 2.12 0.11 0.24 2.01]
 [0.55 0.   0.64 0.15 0.53 3.04 0.44 0.58 2.14 0.19 0.5  5.35 0.68 0.1
  0.68 1.22 0.55 1.16 0.38 0.25]
 [0.51 0.64 0.   5.43 0.27 1.54 0.95 1.13 3.96 0.55 0.13 3.01 0.2  0.1
  0.2  3.97 2.03 0.07 1.09 0.2 ]
 [0.74 0.15 5.43 0.   0.03 0.62 6.17 0.87 0.93 0.04 0.08 0.48 0.1  0.05
  0.42 1.07 0.37 0.13 0.33 0.15]
 [1.03 0.53 0.27 0.03 0.   0.1  0.02 0.31 0.25 0.17 0.38 0.07 0.39 0.4
  0.11 1.41 0.51 0.72 0.54 1.  ]
 [0.91 3.04 1.54 0.62 0.1  0.   5.47 0.33 4.29 0.11 0.87 3.89 1.55 0.1
  0.93 1.03 0.86 0.22 0.23 0.3 ]
 [1.58 0.44 0.95 6.17 0.02 5.47 0.   0.57 0.57 0.13 0.15 2.58 0.32 0.08
  0.68 0.7  0.82 0.16 0.2  0.59]
 [1.42 0.58 1.13 0.87 0.31 0.33 0.57 0.   0.25 0.03 0.06 0.37 0.17 0.05
  0.24 1.34 0.23 0.34 0.1  0.19]
 [0.32 2.14 3.96 0.93 0.25 4.29 0.57 0.25 0.   0.14 0.5  0.89 0.4  0.68
  0.7  0.74 0.47 0.26 3.87 0.12]
 [0.19 0.19 0.55 0.04 0.17 0.11 0.13 0.03 0.14 0.   3.17 0.

Make sure the matrix you obtained is indeed symmetrical:

In [12]:
#Your code here

True


Now, you should multiply each column of this symmetric matrix in its corresponding frequency.
To achieve this:
1. Transform the given vector of frequencies 'p' to a diagonal matrix *D* using `np.diag`.
2. Multiply the symmetrical matrix *S* in the diagonal matrix *D* using `np.dot` and name this matric *R*.


When you multiply a symmetric matrix 𝑆 by a diagonal matrix 𝐷 , each column of the symmetric matrix is scaled by the corresponding diagonal element of𝐷. Print the shape of the obtained matrix.


In [13]:
#Your code here

(20, 20)

Next, generate a normalized matrix named *norm_R* normalize so that the average value across the entire matrix becomes 1. Make sure the mean values across the entire matrix is indeed 1.

In [14]:
#Your code here

1.0


Remember that the diagonal values of our matrix R are currently zero. To make sure, print the diagonal values of the matrix.

In [15]:
#Your code here

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Finally, make the sum of each row to be zero by setting the diagonal value of each row to the negative sum of the other elements in that row. Generate a new numpy array named Q where the diagonal values are adjusted accordingly.

In [17]:
#Your code here

Each **row** in the matrix Q that you obtained represents the subtitution rates of one amino acid with the other amino acids.
